### ISSUE TITLE
Visualize Sound

### ISSUE THREAD

**Issue by sajjadjaved01** [Simsso/SoundCatcher#1]
Hi, i'm new to this, i want to play visualizations on every sound playing / passing  through sound card using wasapi i dont want to write it to wav file, just directly pass that sound into Bass.dll to create visualizations...
Thanks

**Comment by Simsso** [comment]
This repository does not contain any visualization functionality. I do not know how to do that, maybe you want to have a look at FFT.

**Comment by sajjadjaved01** [comment]
I have visualizations, i want to know how can i pass this to my program.
i dont want to record sound, just pass that data to my program
[Here's the link](https://github.com/sajjadjaved01/Player)

**Comment by Simsso** [comment]
Sorry, I'll close this issue since it has nothing to do with this repository.
